### ISSUE TITLE
Implement micro benchmarking tooling for doing MSMs/using GPU on Mobile

### ISSUE THREAD

**Issue by oskarth** [oskarth/mopro#21] opened 2023-10-28 04:43 UTC
Part of https://github.com/oskarth/mopro/issues/22

## Problem

We currently lack basic tooling for doing micro benchmarking on mobile.

## Steps

1. Create `gpu_explorations` folder in [`mopro-core`](https://github.com/oskarth/mopro/tree/main/mopro-core/src/middleware) with `run_msm_bench()` function that runs N MSM, with timings
2. Add and use vanilla [arkworks msm](https://github.com/arkworks-rs/algebra/blob/master/ec/src/scalar_mul/fixed_base.rs#L85)
3. Extend FFI in [lib.rs](https://github.com/oskarth/mopro/blob/main/mopro-ffi/src/lib.rs) and UDL file to support above function
4. Write basic [Swift test](https://github.com/oskarth/mopro/tree/main/mopro-ffi/tests/bindings) to check initial performance on laptop (not mobile/iOS)
5. Add and call above function in the iOS example app [ViewController.swift](https://github.com/oskarth/mopro/blob/main/mopro-ios/MoproKit/Example/MoproKit/ViewController.swift)
6. Run on a real iOS device to check performance
7. Update README with instructions for how to run above; add initial benchmarks observed

## Next steps

After basics are in place, we can do things like:
- Add alternative implementations like https://lib.rs/crates/ark-msm / Zprize work
- Add feature flags for specific dependencies/versions
- Get it to run on iOS GPU
- Do mobile specific optimizations
- Integrate into actual proof systems, etc

## Acceptance Criteria

Basic micro benchmarking tooling is in place with initial numbers running on a real iOS device.

**Comment by oskarth** [comment] 2024-02-23 04:51
@FoodChain1028 @moven0831 can this be closed with https://github.com/oskarth/mopro/pull/71?

Would you like to turn next steps into specific GH issues with acceptance criteria and relevant notes in this repo?

**Comment by moven0831** [comment] 2024-02-23 08:58
The issue is closed by #71.
The next steps of MSM acceleration with mobile GPU will be published in another issue ASAP.

**Closed by moven0831** 2024-02-23 08:58 UTC

**Comment by ssxssx** [comment] 2024-03-04 12:26
Can we still apply for the open task in the https://github.com/privacy-scaling-explorations/acceleration-program/issues/24? May I ask whether this project and task have been finished, and are they no longer open in the acceleration-program?

**Comment by NOOMA-42** [comment] 2024-03-04 15:20
the original acc program issue points at this issue which is wrong, should be https://github.com/oskarth/mopro/issues/15
> Can we still apply for the open task in the [privacy-scaling-explorations/acceleration-program#24](https://github.com/privacy-scaling-explorations/acceleration-program/issues/24)? May I ask whether this project and task have been finished, and are they no longer open in the acceleration-program?
